### ISSUE TITLE
Feature: forward telegram message to notion

### ISSUE THREAD

**Issue by hulloanson** [ansonyuenr2c2/agile-tg-bot#1]
**Why**

Boss wants me to write brief reports on Notion. It is more than a few clicks away and slow to load. In contrast, Telegram is fast, summarizing my stand-ups on Telegram feels intuitive esp. right after a standup meeting. It would be great to type the summary in Telegram and have it forwarded to a Notion page automatically.

**TODOs**

- [ ] Spin up a telegram bot that can catch standup summaries
- [ ] Send the caught standup summaries to a configured Notion page
- [ ] Offer commands in telegram to configure ways to match standup messages and the Notion page to send to
